accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import hello_world, AccountCreateView, AccountUpdateView, AccountDeleteView, AccountDetailView

app_name = 'accountapp'

urlpatterns = [
    path('hello_world/',hello_world,name='hello_world'),

    path('login/', LoginView.as_view(template_name='accountapp/login.html'),
         name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),

    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),

    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),

    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete')
]#name = reverse_lazy 로 연결해주는 연결고리

wolfs_jango_project2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accountapp.urls')),
]

accountapp/models.py
from django.db import models

# Create your models here.

class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False)
    # 마이그래이션을 통해서 db 를 만들고 model 을 통해서 db 의 한줄을 HelloWorld 로 추가 #

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm


class AccountCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True

accountapp/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render


# Create your views here.
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from accountapp.forms import AccountCreationForm
from accountapp.models import HelloWorld


def hello_world(request):
    if request.method == "POST":

        temp = request.POST.get('hello_world_input')

        new_hello_world = HelloWorld()
        new_hello_world.text = temp
        new_hello_world.save()

        return HttpResponseRedirect(reverse('accountapp:hello_world'))
    else:
        hello_world_list = HelloWorld.objects.all()
        return render(request, 'accountapp/hello_world.html',
                      context={'hello_world_list': hello_world_list})

class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/create.html'

class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'

class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountCreationForm #말그대로 장고 기본 제공해주는 Creattion Form
    context_object_name = 'target_user' #update.html에서
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/update.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return super().get(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse('accountapp:login'))

    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return super().post(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse('accountapp:login'))
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/delete.html'

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}

{% block content %}

    <div class="text-center">
        <div class="m-5">
            <h4>Sing Up</h4>
        </div>
        <div>
            <form action="{% url 'accountapp:create' %}" method="post">
                {% csrf_token %}
                {{ form }} {# ? #}
                <div class="m-5">
                <input type="submit"
                       class="btn btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Delete Account</h4>
        </div>
        <div>
            <form action="{% url 'accountapp:delete' %}" method="post">
                {% csrf_token %}
                <div class="m-5">
                <input type="submit"
                       class="btn btn-danger rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>{{  target_user.username }}</h4>
        </div>
        <div>
            {{ target_user.date_joined }}
        </div>
        {% if user == target_user %}
        <div>

            <a href="{% url 'accountapp:update' pk=target_user.pk %}">
                Update Info
            </a>
        </div>
        <div>
            <a href="{% url 'accountapp:delete' pk=target_user.pk %}">
                Quit
            </a>
        </div>
        {% endif %}
    </div>

{% endblock %}

accountapp/templates/accountapp/hello_world.html
{% extends 'base.html' %}

{%  block content %}

    <div style = 'margin: 2rem; text-align: center'>
        <h1 style="font-family:  'Pacifico', cursive"
            class="m-5">
            hello world list
        </h1>

        <form action="/account/hello_world/" method="post">
            {% csrf_token %}
            <div class="input-group wb-3 w-50 m-auto">
                <input type="text" class="form-control"
                       name="hello_world_input">
                <button class="btn btn-dark" type="submit">
                    Button
                </button>
            </div>
        </form>
        {% if hello_world_list %} {# 만약 hello_world_output 이 있으면 #}

            {% for hello_world in hello_world_list %}
                <h3>{{ hello_world.text }}</h3> {# get method 불러옴 #}
            {% endfor %}
        {% endif %} {# endif 로 막아줘야됨 #}
    </div>

{%  endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{%  load bootstrap4 %}
{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Login</h4>
        </div>
        <div>
            <form action="{% url 'accountapp:login' %}" method="post">
                {% csrf_token %}
                {%  bootstrap_form form %}
                <div class="m-5">
                <input type="submit"
                       class="btn btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Update Info</h4>
        </div>
        <div>
            <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="m-5">
                <input type="submit"
                       class="btn btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% include 'head.html' %}

<body style="font-family: 'NanumSquareR'">
{%  include 'header.html' %}

{%  block content %}
{% endblock %}

{% include 'footer.html' %}
</body>
</html>

templates/footer.html
<div style = 'text-align: center'>
    <div style="font-size: .8rem; margin: 1.5rem;  ">
        <span>공지사항</span>
        <span>제휴 문의</span>
        <span>서비스 소개</span>
        <span>asdfasdf</span>
    </div>
    <div class="woolf_footer">
        <h3>woooo</h3>
    </div>

</div>

templates/head.html
{% load static %}

<head>
    <style>
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.ttf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareEB';
            src: local('NanumSquareEB'),
            url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareB';
            src: local('NanumSquareB'),
            url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
        }
    </style>
    <meta charset="UTF-8">
    <title>Title</title>

    {# BOOTSTRAP LINK #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    {# GOOGLE FONTS LINK #}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Otomanopee+One&display=swap" rel="stylesheet">

    {# STATIC FILES LINK #}
    <link rel="stylesheet" type="text/css" href="{% static 'base.css'%}">
</head>

templates/header.html
<div style = 'text-align: center'>
    <div style="margin: 2rem 0;">
        <div class="wolf_header_log">
            <h1>Woolf stroy</h1>
        </div>
    </div>
    <div class="wolf_header_btn">
        <span>wo1</span>
        <span>wo2</span>
        {%  if not user.is_authenticated %}
        <span>
            <a href="{% url 'accountapp:login' %}">
                Login
            </a>
        </span>
        <span>
            <a href="{% url 'accountapp:create' %}">
                Sign Up
            </a>
        </span>
        {% else %}
        <span>
            <a href="{% url 'accountapp:detail' pk=user.pk %}">
                My page
            </a>
        </span>
        <span>
            <a href="{% url 'accountapp:logout' %}">
                Logout
            </a>
        </span>
        {% endif %}
    </div>
</div>